## ===============================
## = DATA SOURCE
## ===============================
## Set here configurations for the database connection
#spring:
#
#  datasource:
#    url:  jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_d7b8aeef2f568e0?reconnect=true
#    # Username and secret
#    username:  b7e4997aad2d9e
#    password:  86db03ae
#    # Keep the connection alive if idle for a long time (needed in production)
#    testWhileIdle:  true
#    validationQuery:  SELECT 1
#  jpa:
#    show-sql:  true
#    hibernate:
#      ddl-auto: update
#
#      # Allows Hibernate to generate SQL optimized for a particular DBMS
##    properties:
##      hibernate:
##        dialect:  org.hibernate.dialect.MySQL5InnoDBDialect
#
#file:
#  upload-dir: ./uploads
#  upload-dir-tmp: uploads/tmp
#
#server:
#  port: 8080
